#+title: About posdcast player
#+date: <2023-10-14 Sat>
#+category: Essay
#+language: English
#+tags: posdcast

I have been listening to podcasts since the summer of 2021.

[[https://www.xiaoyuzhoufm.com][Xiaoyuzhou]] is my first podcast client on my Android phone. When I tried to listen to music on Netease Music or watch videos on Bilibili in real-time, I found myself only listening to Chinese podcasts. Until the winner of the next year, I learned about economics, technology, nutrition, and crypto. It's a good platform in China. It has special features like comments, an all-in-one inbox, and the ability to track how much time you spend listening. In the summer of 2023, I had listened for 500 hours.

However, Xiaoyuzhou is a specialized platform in China. Everyone must log in with their real number or WeChat account, and it is heavily regulated in terms of its podcast content. Many funny podcast channels about politics and full English channels cannot be found on it. So I searched for a podcast client on the Play Store. A good choice I found was Google Podcasts. I tried it for only a week because it was too difficult compared to Xiaoyuzhou and lacked advanced configuration options.

During the Lunar New Year, I downloaded many applications like Spotify, Podcast Player, and Pocket Casts. It was hard to find a good podcast client like the Apple Podcast in the Apple ecosystem, so I went back to Google Podcasts.

However, this summer, Google announced that Google Podcasts will be shutting down in 2024 in favor of YouTube Music. I couldn't believe it when I tried listening on YouTube Music without ads. So now I have to find another app.

Some users on Telegram told me about an open-source podcast player called [[https://antennapod.org][AntennaPod]], which is ad-free and has a user interface designed with the Material Design ecosystem. It took me at least one month when write this article. It's fully configurable, but refreshing and getting all subscriptions one by one is too slow. There are differences compared to server-based podcast players, but I can understand them.

